# Generated by Django 5.0.4 on 2024-04-18 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth_user', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_default_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_inventory_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_inventory_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_inventory_tl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_operational_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_receptionist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_security',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_warehouse_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_warehouse_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_warehouse_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_warehouse_tl',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('personal_email', models.EmailField(max_length=254, unique=True, verbose_name='Personal Email')),
                ('contact_number', models.CharField(max_length=35, verbose_name='Contact Number')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.address', verbose_name='Address')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_auth_user.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
            },
        ),
    ]
