# Generated by Django 5.0.4 on 2024-04-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth_user', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.address', verbose_name='Address'),
        ),
    ]
